### ISSUE TITLE
Navigate between scenes in the scene editor

### ISSUE THREAD

**Issue by Harshal-D** [UoaWDCC/VPS#21]
## Issue Description

Once a scene has been opened for editing inside of a scenario, there is no way to be able to navigate to the next or previous scene. We would like to add this functionality.

## User Story

"As an editor, I would like to navigate through the different scenes in the scenario so that I can view and make changes without the need to close and open multiple editors."

## MVP

MVP for this feature would be to have functioning "Next" and "Previous" buttons at the bottom of the editor.

(Going beyond MVP would be to have thumbnails preview sidebar/bottom-bar as seen in the likes of PowerPoint or numerous PDF editors)

## Tasks

- [x] Create "Next" and "Previous" buttons and adjust the editor interface to be able to accommodate the buttons into the UI
- [x] Implement functionality of the buttons (be able to move between scenes)
- [x] Make sure functionality covers edge cases (such as there only being one scene therefore buttons would be greyed out etc..)
- [x] Create a side (or bottom) pane showing thumbnail preview for "one-click" navigation to a given scene in the scenario.

**Comment by nickykay98** [comment]
@KW781 @DamonGreenhalgh @retinfai Note that I only talked about the PowerPoint preview side of things, not necessarily the "Next" and "Previous" buttons on each scene (as described above) which would also be awesome to implement but up to you as to whether to include one or the other or both!

**Comment by retinfai** [comment]
@KW781 @DamonGreenhalgh was thinking about it throughout the meeting and implemented a potential mechanism for switching between scenes. 

Explanation
-
Used context to get the array of scenes for scenario (still don't know how the magic works but alg aha)
Then a simple `setCurrentScene(array[indexOfCurrentScene +/- 1])` when next/before button clicked
And it works

Some things that haven't been considered and might not work:
-
- Saving across navigation
- URL not updating on navigation

Lmk what you think

**Comment by DamonGreenhalgh** [comment]
@retinfai @KW781 I have added the navigation bar to the left. 
- Saving a newly selected scene does not work. For example if you select _scene 2_ from the scene selection page but then moved to _scene 3_ using the scene navigator, trying to save _scene 3_ will instead **overwrite** _scene 2_ with the content of _scene 3_. Pretty sure the fix to this bug would involve the `monitorChange`, `hasChange`, and `reFetch` variables in `SceneContextProvider.js`. 
- The thumbnails to the left use the `Thumbnail` component which takes in a url parameter to build a thumbnail of the page. So all the previews we see are thumbnails to the **play** version of scenes. 
- Selecting a scene **does change the url**, but ultimately the save functionality is the big problem here to resolve. 

Below is a preview of the component.

![image](https://user-images.githubusercontent.com/59471444/171141177-720ce3f8-5c3c-418f-a94e-f0d69d7ce2ef.png)

**Comment by retinfai** [comment]
Yoo that looks really good man

**Comment by DamonGreenhalgh** [comment]
@retinfai @KW781 I fixed the saving problem. You can now edit and save different scenes without the need of going back to scene selection and selecting the scene to edit. I also added a slide number to the left of each thumbnail.

![image](https://user-images.githubusercontent.com/59471444/171314856-4edf7009-d8f8-4317-8373-3373322823ab.png)

@nickykay98 @Harshal-D  I have a few questions regarding the save behavior when switching between scenes. Currently you can switch to a new scene using the scene editor to edit a scene, but you **MUST** save the scene before switching to another scene or you will lose changes. 

I imagine the ideal behavior would automatically save the scene on the following actions,

- User **edits** the scene (adds component, changes text, etc)
- User **switches** to another scene
- User **leaves** editor

If the above is implemented the save button on the top bar becomes redundant and users also lose the ability to make changes without saving. Let me know your thoughts on this and how we should approach this. Thanks!

**Comment by nickykay98** [comment]
@DamonGreenhalgh Looks fantastic! I think the saving functionality could be modified like below which keeps the ability to make changes without saving:
- User edits the scene (adds component, changes text, etc): changes don't get saved until the user
  - clicks Save/Save and Close (in which case, it would be good to keep the existing buttons)
  - leaves the editor (already handled with the warning that comes up if you haven't saved) but clicks Save in the warning
  - switches to another scene (changes in the current scene, if any, could get saved automatically)

@retinfai @KW781 Keen to know what you guys think since you two worked on the saving functionality in the last sprint 😄

**Comment by retinfai** [comment]
I agree with @DamonGreenhalgh that given the ideal scenario as described, the save button would become redundant. Possibly also the back button – which would then be replaced with the `saveAndClose` button.

With regard to the users losing the ability to make changes without saving – I believe the future implementation of **document history** would address this issue directly.

**Comment by KW781** [comment]
I agree with most of what @DamonGreenhalgh has said, except for the part about automatically saving with each edit (unless I'm misinterpreting it?). I think the user should be able to make edits to an individual scene without necessarily saving it, that way those changes can be reversed if they're not satisfied with it. 

I'm not fully sure how the document history will be implemented, but even if it would allow the user to restore the scene to a previous version, I still think they should be provided with an easy way to just reverse all the changes they have made at any given point in time to restore to the most recent saved version, rather than having to dig through a document history. 

Another concern I have is with the implementation of the document history if we will be saving for every individual edit is that the document history will be very large and unwieldy for the user to navigate. 

As far as the the save button being redundant goes, assuming that we will not save with every individual edit, then I think the save button should remain as an additional option available to the user. 

Just my two cents though.

**Comment by retinfai** [comment]
@KW781 I agree, document history could become tedious for users who just want to discard changes.

Perhaps saving at the level of the scenario as opposed to the level of the scene is better. Where, a user can edit many scenes and then save the whole scenario at one time – at the scene selection page. And if they try to leave the scene selection page without saving then prompt the user to save or discard changes.

**Comment by KW781** [comment]
Yeah I think that perhaps that might be good, but alongside the current save functionalities in individual scenes so that the user can still save an individual scene without saving other scenes.

And perhaps if we are implementing a save functionality for the overall scenario, then when implementing the document history we could store a document history for the overall scenario rather than each individual scene? So we would only append to the document history when the user saves the entire scenario. That way, the document history won't necessarily become large and unwieldy for the user to navigate.

**Comment by DamonGreenhalgh** [comment]
Some minor changes,

- Changed style. Added border effect to indicate current scene (green) and hovered scene (grey).
- Now automatically saves when switching to another scene.
- Supports overflow, can scroll to view more slides.

![image](https://user-images.githubusercontent.com/59471444/171841829-6a4d130a-9d74-4005-8373-2c42a812521a.png)

**Comment by Harshal-D** [comment]
@DamonGreenhalgh Looks great! I agree with the auto-save when switching between scenes, seems like a nature interaction for the user. 

@KW781 @retinfai I agree, I think if document history functionality were to be implemented it might make it easier having it for the scenario. In terms of save behaviour as whole, I think @nickykay98 comment above sums it up well as what the ideal and in my opinion what the most useful and natural behaviour would be. Some good discussion, eager to hear more of your  thoughts.

**Comment by DamonGreenhalgh** [comment]
Fixed the following issues,

- Navigator cropping at smaller resolutions.
- `currentScene` variable not updating when selecting a scene. (When users select a scene to edit in the scene selection page, it now correctly shows the currently selected scene in the navigator.)

@KW781 @retinfai Check if the app is behaving correctly after the most recent commits.

**Comment by KW781** [comment]
I've configured the 'Save' button so that it shows a confirmation to the user when it's clicked, similar to what @nickykay98 described in meeting. Nothing too fancy, just changes the button text for a couple seconds and then it reverts back to the default text. Let me know if you need something fancier than this.

**Comment by retinfai** [comment]
Oops sorry bro, I just pushed changes for the enable/disable for the next buttons. Can you rerequest the PR.

However, the refreshing issue is still messing with the next buttons, and I still don't know how to fix it. I'd like some help pls, if you got any ideas. 

@DamonGreenhalgh I tried looking at how you fixed it, and am I right by saying that you made your component dependent on currentScene directly and not indirectly through another index state? I've tried doing the index method and am stuck here atm.

@KW781 also the save looks real sweet

**Comment by nickykay98** [comment]
@retinfai @DamonGreenhalgh @KW781 Just checking you're all done before I merge the PR? 😄

**Comment by DamonGreenhalgh** [comment]
Yep, ready for PR. Sorry for late response, just finished exams.

**Comment by nickykay98** [comment]
Thanks @DamonGreenhalgh @KW781 @retinfai 

If there's any "lorem ipsum" type text or blank text fields, can you guys please replace it with something that might make more sense for a user? This is just for the purposes of demo-ing the app to sponsors at the AGM, we can finalise the actual text later

**Comment by DamonGreenhalgh** [comment]
@nickykay98 @Harshal-D There is no dummy test in this specific feature. But the help modal from the previous sprint does.

![image](https://user-images.githubusercontent.com/59471444/176088897-b4e7cdcc-1659-43a2-bde0-a9b1cd5416e1.png) 

What would be the best approach to replace this text, open new issue/branch then PR or use this branch?

**Comment by nickykay98** [comment]
@DamonGreenhalgh I think just something like "Welcome to the Virtual Patient Simulator! To create a new scenario, click Create and start adding scenes. To play an existing scenario, click Play. To edit an existing scenario or the scenes within it, click Edit. To delete a scenario, click Delete." would be sufficient

 (@Harshal-D would that be enough to show at the AGM?)
