### ISSUE TITLE
Add timer functionality to scene

### ISSUE THREAD

**Issue by Harshal-D** [UoaWDCC/VPS#22]
## Issue Description

To be able to add a time constant to the scene. After the timer ends, the scene can either end or prompt for restart.

## User Story

"As an editor, I would like to add a timer to the scene, so that I can add a time constraint to the scene."

"As a player, I would like to be able to see a timer, so that I can see how much time is left to play the scene."

## MVP

MVP for this story is being able to add a timer for each scene, allowing the editor to customise how much time a user can spend on any given scene. At the end of the timer there will be a prompt (either pop-up stopping the scenario or prompting for a restart).

An extension of this could involve adding a timer scenario. This could even be for specific components inside a scene e.g. a button, image etc that only appears for a certain amount of time

AND 

For the timer to be present when playing the scenario.

## Tasks

~~- [ ] Add the timer tool to the toolbar (scene editor)~~
~~- [ ] Setup params for timer tool~~
    ~~- [ ] Timer length~~
    ~~- [ ] Action to be completed at the end of the timer~~
    
- [x] Having a button/field to input timer duration (done on scene page) - Lia
- [x] When the scene is created, send this time to the database - as each scene is already posted to the database, this can be done by just adding a field - Aden
- [x] Render timer component on scene, need to fetch initial countdown time from database - Josh
- [x] Have some sort of alert/modal pop up when timer reaches 0 - and then take the user back to the original page? - Matthew

**Comment by nickykay98** [comment]
@jfen445 @lia-arroyo @aadenmann Updated the issue description so that it's consistent with the "scenario"/"scene" terminology we're going to use going forward + after what we discussed, feel free to edit! 😊

**Comment by Harshal-D** [comment]
@mlai962 @jfen445 @lia-arroyo @aadenmann Updated the issue description in line with what was discussed in todays dev session - Adding a timer to the scene.

**Comment by nickykay98** [comment]
> @mlai962 @jfen445 @lia-arroyo @aadenmann Updated the issue description in line with what was discussed in todays dev session - Adding a timer to the scene.

Just to add on, regarding how you could go about splitting this up, here are a few ideas from today's meeting:
- 1-2 people working on the component to set the time for each scene (I believe @jfen445 said he started researching this)
- 1-2 people on the backend logic for counting down the timer
- 1-2 people working on the end state (what happens when the timer runs out e.g. screen pops up saying timer has run out with button/s allowing user to go to the list of scenarios, the next scene, or whatever you think is appropriate)

**Comment by lia-arroyo** [comment]
Josh's breakdown of tasks: 

- [ ] Having a button/field to input timer duration (done on scene page) - **Lia**
- [ ] When the scene is created, send this time to the database - as each scene is already posted to the database, this can be done by just adding a field - **Aden**
- [ ] Render timer component on scene, need to fetch initial countdown time from database - **Josh**
- [ ] Have some sort of alert/modal pop up when timer reaches 0 - and then take the user back to the original page? - **Matthew**

Branch: [VPS-022/timer](https://github.com/UoaWDCC/VPS/compare/VPS-022/timer)

**Comment by nickykay98** [comment]
> Josh's breakdown of tasks:
> 
> * [x]  Having a button/field to input timer duration (done on scene page) - **Lia**
> * [ ]  When the scene is created, send this time to the database - as each scene is already posted to the database, this can be done by just adding a field - **Aden**
> * [ ]  Render timer component on scene, need to fetch initial countdown time from database - **Josh**
> * [ ]  Have some sort of alert/modal pop up when timer reaches 0 - and then take the user back to the original page? - **Matthew**
> 
> Branch: [VPS-022/timer](https://github.com/UoaWDCC/VPS/compare/VPS-022/timer)

@lia-arroyo Looks great, thanks @jfen445! Added this list in the Tasks section above @mlai962 @aadenmann  😊

**Comment by lia-arroyo** [comment]
Hi guys! I managed to limit the scene timer duration to positive numbers only as you can see here: [Loom Video](https://www.loom.com/share/fdd77aa788e24f50805935c20ad7cc48) 

#### Some issues/concerns to take care of next time:
- **There isn't a clear way for users to indicate that they don't need a timer for the scene.** At the moment, setting it to 0 and not entering a value does this, but this could cause confusion in the future. Matthew suggested potentially adding a 'no time limit checkbox'. 
-  **Material UI Shrink label overlap.** Since the shrink is managed manually, adding any '-' or '+' symbols (which is allowed in the number field) causes the overlap to occur, so need to remove this ability. 
Also, the label doesn't move when clicked, unless you enter a value (which is inconsistent with the 'Scene Name' field shrink animation). 

I'll do the PR now :)
