### ISSUE TITLE
Implement prototype dashboard

### ISSUE THREAD

**Issue by nickykay98** [UoaWDCC/VPS#32]
## Issue Description

Implement the prototype dashboard created in Figma in the last sprint into the app (just the frontend, other people are working on the backend logic)

## User Story

User stories to help describe what the functionality is meant to be able to achieve.

## MVP

A prototype dashboard linked to the existing button created by @mlai962 in the last sprint, inspired by the prototypes created in the last sprint too ([original issue linked here](https://github.com/UoaWDCC/VPS/issues/28), [folder of prototype screenshots linked here](https://drive.google.com/drive/u/1/folders/1SagbpzECNgFhbIi_Uq_dvsNcnEfv5zl9))

The screenshots look great but not all of the dashboard may be able to be implemented yet, so just try your best and see what you can accomplish in this sprint!

## Tasks

Describe the tasks in this story.

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by nickykay98** [comment]
@mlai962 @retinfai Me and @Harshal-D have 

Note that a branch has already been created [VPS-032/implement-prototype-dashboard](https://github.com/UoaWDCC/VPS/tree/VPS-032/implement-prototype-dashboard) but Matthew's changes from the last sprint still need to be merged once Lia reviews the PR, so pull from master once that's done!

**Comment by nickykay98** [comment]
Continuing to be worked on in sprint 5

**Comment by retinfai** [comment]
# Sprint 6.1 Update
Decided to move forward with [React Flow](https://reactflow.dev/) for graphing.

Damon and I talked about the graph/mapping requirements needed for the graph UI implementation.
– Graph class will implement **adjacency list** representation of paths

## Potential Features:
### Heat Map Colour Scheme:
Node colour determined by metric such as how many times node is visited 

### Most Path, Path Style
Animate the most popular path for easy usage

### On Click/Hover details panel
Click/Hover on graph node for a more detailed view of the data stored at that node

## Updated TODO:

- [ ] Load graph data into graph UI
- [ ] Dynamically calculate positioning of nodes
- [ ] On click/hover details panel

## Final Comments
Rebase branch or create anew after everyone has successfully merged last sprints work into main. We will commence work after this is done as our work depends on everyone elses

**Comment by retinfai** [comment]
@nickykay98 and @Harshal-D, should we wait for the merge to main before rebasing or should we rebase now and just merge what feature branches we need into our own

**Comment by nickykay98** [comment]
@retinfai Merging Damon's stuff soon (see open PR), so rebase from main once that's done since that's probably the main work you need

**Comment by mlai962** [comment]
After pulling Alfred's changes with the graph, I ran npm install and yarn install in the frontend and backend folders to download the dependencies that Alfred added, the app opens to the home page but I can't click anything and there are errors in the terminal. Not sure why the home page is displaying despite the compile errors. 
![image](https://user-images.githubusercontent.com/79812370/189825406-47716a4e-8386-4d16-a625-4a418854d782.png)

**Comment by nickykay98** [comment]
> After pulling Alfred's changes with the graph, I ran npm install and yarn install in the frontend and backend folders to download the dependencies that Alfred added, the app opens to the home page but I can't click anything and there are errors in the terminal. Not sure why the home page is displaying despite the compile errors. ![image](https://user-images.githubusercontent.com/79812370/189825406-47716a4e-8386-4d16-a625-4a418854d782.png)

@retinfai?

**Comment by retinfai** [comment]
We're still trying to work out why this is happening, we've checked that the package.json and lock file contains the dependency. Still feeling out potential issues

**Comment by mlai962** [comment]
Can someone else see if they can run the code on this branch? @nickykay98 @Harshal-D

**Comment by mlai962** [comment]
Still not sure what caused the error but re cloning the repo fixed it.

**Comment by nickykay98** [comment]
@mlai962 @retinfai Sorry, was just gonna run this but had issues with my machine... hoping the recloning isn't a temporary fix, something to discuss tomorrow maybe

**Comment by nickykay98** [comment]
Continuing to be worked on in sprint 7
