### ISSUE TITLE
Create game layer to track progress

### ISSUE THREAD

**Issue by nickykay98** [UoaWDCC/VPS#33]
## Issue Description

Create a game layer that enables things like progression tracking by converting a scenario and its scenes into a graph representation

See minutes from 3/8/22 for more details: https://docs.google.com/document/d/1tK8Goe7VbGD-C0zOAQzgCRt4Zg3RCA6aZ1Z6QVdvDkQ/edit?pli=1#bookmark=id.9qj4xihvb8lv

## User Story

"As a user, I want the app to track my progress as I play a scenario"

## MVP

This one's a little tricky, but something like a graph representation of a scene and backend functionality to calculate things like how many scenes are left until the end scene.

## Tasks

Describe the tasks in this story.

- [x] Create endpoint that returns a graph representation of the scenario
- [x] Create Graph class
- [x] Create method to track the distance between any two scenes
- [x] Create method to track the progress of a player

**Comment by nickykay98** [comment]
@DamonGreenhalgh Me and @Harshal-D have decided to have you just work on this for now (Alfred and Matthew will implement the dashboard)! If you want, please add to the issue description, user story, and MVP above based on your discussions with Ray and anything else you find

**Comment by DamonGreenhalgh** [comment]
@nickykay98 I was able to create a new endpoint which returns a graph representation of the scenario in the form of an adjacency list (with other useful fields).

![image](https://user-images.githubusercontent.com/59471444/183403502-a47041b9-5c72-4fcf-860a-03be3d0c05da.png)

Which represents the following graph, 

![image](https://user-images.githubusercontent.com/59471444/183405398-d7913d24-0cab-4b66-b01e-9ab9b5a94784.png)

Next step would be computing the progress to the nearest end node.

**Comment by nickykay98** [comment]
@DamonGreenhalgh Awesome, glad it's working, thanks for the update! Let's chat more about this tomorrow with @Harshal-D and the team 😄

**Comment by nickykay98** [comment]
@DamonGreenhalgh All good! Let us know if you need us to do anything that you don't have access to 👍

**Comment by DamonGreenhalgh** [comment]
@nickykay98 @Harshal-D @Ray-F I have added a new method to the graph class that will compute the distance between any two scenes. 

It returns -1 under the following conditions,

- the end scene does not exist within the graph
- there is no directed path from start scene to end scene

I built a more complex scenario to test if this method worked. The following graph is was designed with respect to the distance from the root. Note: any arbitrary scene can be selected as the root node.

![image](https://user-images.githubusercontent.com/59471444/184066202-38f4f696-bff1-4cec-a2ef-229959dc6000.png)

Using the method we get the following results,

![image](https://user-images.githubusercontent.com/59471444/184067791-7b2bdd8f-7ccc-47bb-bcf4-380bada9dfe2.png)

But we can choose any start scene, lets select scene 5,

![image](https://user-images.githubusercontent.com/59471444/184068233-ca578360-092f-46fe-95ae-c30c59191b30.png)

This is not far off what is required to extract the progress of the player, some slight modifications can be done to achieve this.

**Comment by nickykay98** [comment]
> 

@DamonGreenhalgh This is actually so cool, will definitely show this to the client next Monday, keep up the awesome work!!

**Comment by Harshal-D** [comment]
Awesome stuff @DamonGreenhalgh!

**Comment by DamonGreenhalgh** [comment]
@nickykay98 @Harshal-D I got it working! The progress bar will now accurately represents the progress along the scenario.

I did a few changes to get it working. First as per @Ray-F 's suggestion, I used Floyd's algorithm to generate all pairs shortest paths and stored those distances within a 2D distance map. In this format fetching the distance between any two scenes takes constant time over O(V^3) before. 

Getting the relative progress based on the current scene was not much harder to implement. I created a new method that returns a number between 0 and 1 inclusive. To get this value I used to following formula,

> distance from root to current / (distance from root to current + distance from current to **furthest** end scene)

To check for correctness I looped over the scenes and logged the supposed progress values. 

![image](https://user-images.githubusercontent.com/59471444/185732391-1f802321-6c07-4d7d-9bdf-1e2835f3fb08.png)

I then linked to the front-end by creating a new temporary endpoint and updated the ProgressBar component to use the new endpoint.

https://user-images.githubusercontent.com/59471444/185731941-f7c6d89c-99cc-4531-9379-8dfee00ce8b1.mp4

Few things to work on,

 - Backwards progress, going from 40% to 20% due to a directed cycle. But this can be fixed by using max(previous progress, current progress).
 - Caching the graph so we only need to initialize it once when the player begins a scenario.

**Comment by nickykay98** [comment]
@DamonGreenhalgh Awesome work!! Would you mind demoing all this on Wednesday and thinking about how more of the team can jump on to build this out (just to help us plan sprint 5 that day haha)? 

Because as you might have also seen from the client meeting notes, we're going to keep working on the graph stuff across the whole stack so it would be good to have more of the team working closely with what you've developed 😄
